### ISSUE TITLE
Demo isn't working anymore

### ISSUE THREAD

**Issue by RayBB** [caljp13/iCloud-Album-Downloader#1]
Looks like the demo isn't working anymore.
It says
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://icloud-album-downloader.herokuapp.com/api/B14GWZuqDQpCMm. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 404.

I assume this is because Heroku took down the free tier :/

Might want to put a note about it in the repo if you think you'll still maintain it.

How I got it working:
run: `node server/server.js`
Edit index.html and replace `https://icloud-album-downloader.herokuapp.com/api/` with `http://localhost:5000/api/` 
Open `index.html` in your browser and walla.

PS: This repo is a nice wrapper around https://github.com/ghostops/ICloud-Shared-Album

**Comment by cvscarlos** [comment]
@RayBB thank yopu for reporting, the demo is working again.
